version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        - VCS_REF=$(git rev-parse --short HEAD)
        - VERSION=$(node -p "require('./package.json').version")
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://eskan-real-estate-backend.onrender.com/api
    depends_on:
      - backend
    networks:
      - real-estate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Backend Node.js Application
  backend:
    image: nginx:alpine
    ports:
      - "5000:80"
    environment:
      - BACKEND_URL=https://eskan-real-estate-backend.onrender.com
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - real-estate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  real-estate-network:
    driver: bridge

volumes:
  uploads:
    driver: local